from __future__ import annotations

from pathlib import Path
from typing import Any

from genesis_framework.generators.base import Generator


class PlaceholderGenerator(Generator):
    def generate(self, canonical_spec: dict[str, Any], output_dir: Path) -> list[Path]:
        output_dir.mkdir(parents=True, exist_ok=True)
        readme = output_dir / "README.md"
        app_name = canonical_spec.get("app", {}).get("name", "Generated App")
        readme.write_text(f"# {app_name}\n\nGenerated by NoCode2ProCode by TrustEngines.\n", encoding="utf-8")
        return [readme]

